version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: cloud9-mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HUmmer512!!!"
    ports:
      - "1433:1433"
    volumes:
      - /srv/cloud9/mssql:/var/opt/mssql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: cloud9-app
    restart: always
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=Cloud9.2;User Id=sa;Password=HUmmer512!!!;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    volumes:
      - /srv/cloud9/dpkeys:/var/dpkeys
    networks:
      - app-network

networks:
  app-network:
    driver: bridge